### ISSUE TITLE
Are curtain motors not supported?

### ISSUE THREAD

**Issue by sup4ri** [iklein99/homebridge-smartthings#104]
**Describe Your Problem:**

I don't see curtain motors on Homebridge.
I am using Aqara curtain motor, Tuya curtain motor.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by iklein99** [comment]
I might be able to add support for that.  IF you want me to look into this, follow these steps:

1. Delete your log files (truncate)
2. Set Debug mode on and restart homebridge
3. After about 30 seconds, download the log file
4. Reset the debug flag (off)
5. Restart homebridge
6. Send the log file to me at iklein99@comcast.net. Include the name you gave to the device.
