### ISSUE TITLE
Washing Machine/Dryer Support

### ISSUE THREAD

**Issue by brades1607** [iklein99/homebridge-smartthings#112]
Firstly, fantastic plugin! So glad someone is working on SmartThings.

Is there a chance we can look into Washing Machine/Dryer support? Currently shows as a switch but doesn't trigger anything.

Thanks!

**Comment by iklein99** [comment]
Unfortunately, there is no service type supported by homebridge such as a washing machine.  You can see all of the service types here: https://developers.homebridge.io/#/.  Look under Service Types.
