### ISSUE TITLE
Hue Bulb not exposed to homebridge

### ISSUE THREAD

**Issue by drpimples** [iklein99/homebridge-smartthings#114]
I just added a Hue white dimmer bulb directly to the SmartThings hub as a zigbee bulb.  Works fine.  The IDE shows it listed as a ZLL dimmer bulb.  Problem is that it won't show up as an accessory on Homebridge even after I've rebooted the container.  Lately I've been manually switching devices over and reincluding them using the Edge drivers and once they show up on SmartThings a reboot will show the newly added device to homebridge / homekit without a problem.  What kind of debugging can I do to help?

**Comment by iklein99** [comment]
Truncate your logs, put homebridge in debug mode, restart and let it run for about 30 seconds to load devices.  Then download the log file and send to me at iklein99@comcast.net.

Let me know the name of the device that you are having issues with

**Comment by drpimples** [comment]
Hey Ira.  Just checking if you got my email the other day with my logs.  The device is Sitting Lamp.

**Comment by iklein99** [comment]
Seems you have it in the “Ignore Devices” list.  I’m seeing this in the log…

Ignoring Sitting Lamp because it is in the Ignore Devices list

**Comment by drpimples** [comment]
That did it.  Thanks again.
