### ISSUE TITLE
Zooz ZSE18 motion sensor not showing temperature

### ISSUE THREAD

**Issue by drpimples** [iklein99/homebridge-smartthings#115]
Just converted the Zooz ZSE18 motion sensors over to the Edge drivers successfully but only motion and vibration detection is showing, but no temperature.  Do you think it may be the Edge drivers not reporting temperature any more?

**Comment by iklein99** [comment]
Same as last issue.  Send me the logs and let me know the name of the devices

**Comment by drpimples** [comment]
Turns out the ZSE18 doesn’t report temperatures.  I swore it did…
