### ISSUE TITLE
Lights unresponsive in HomeKit

### ISSUE THREAD

**Issue by kevininor** [iklein99/homebridge-smartthings#123]
Smartthings lights cannot be controlled from Apple Home and cannot be change from type switch.  Commands work between HOOBS and Smartthings.  Only the initial power on command works from HomeKit.  Status in HomeKit doesn't update and future commands fail.

**To Reproduce:**
Open light in Apple Home, change Display As to Light, remains as switch

**Expected behavior:**
Display As changes to Light

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.4.23
* **Homebridge Version**: 1.50
* **Node.js Version**: 16.19.0
* **NPM Version**: 9.2.0
* **Operating System**: Raspbian

**Comment by iklein99** [comment]
Please send me the detailed log files by following the attached instructions.  Let me know the name of the device you are having trouble with.
[Instructions for Producing a Detailed Log.pdf](https://github.com/iklein99/homebridge-smartthings/files/10446508/Instructions.for.Producing.a.Detailed.Log.pdf)

**Comment by kevininor** [comment]
Thanks for the reply.  I'm working on the logs and will get them generated tonight.  In short, I'm experiencing the lack of control issue with all switches.  Everything between Smartthings and HOOBS is working properly.  It's between Home and HOOBS where the problem lies.  The only command that seems to work from Home is a power on.  All other commands seem to be ignored and status never flows up to Home.  Status and control in HOOBS is always up-to-date and working.

**Comment by kevininor** [comment]
So...  I was having some other issues with my HOOBS installation so I performed a Factory Reset and re-added all bridges from scratch.  Since then, all of the Smartthings lights and plugs came in and can me managed as expected.
