### ISSUE TITLE
Not connecting in HomeKit App

### ISSUE THREAD

**Issue by coolcatiger** [iklein99/homebridge-smartthings#128]
I can see all the devices in hoobs. But when adding to the homekit app, I am unable to add devices.
The Home app gives an error, "Accessory Not Found, Make sure your accessory is powered on and connected to your router with an Ethernet cable, then try again." I have 107 devices.

**Comment by j1104c** [comment]
same issue

**Comment by iklein99** [comment]
You'd have to send me your logs.  Follow the instructions here.  Make sure you email them directly to me and not post them here.  Don't just reply to the email...
[Instructions for Producing a Detailed Log.pdf](https://github.com/iklein99/homebridge-smartthings/files/10483188/Instructions.for.Producing.a.Detailed.Log.pdf)

**Comment by j1104c** [comment]
ok sent to you

**Comment by iklein99** [comment]
I don't see any errors.  The plugin is pushing the devices to homebridge's cache and getting update from them.  No errors.  Not sure why you don't see the devices. 

Try removing and then re-adding the plugin.  Make sure you are using the latest version (1.4.23).

**Comment by coolcatiger** [comment]
I also sent the log to you.

**Comment by coolcatiger** [comment]
I found the issue. I have two Wi-Fi SSID’s one for general use and another for IOT devices. Once I switched my iPhone to the SSID used for IOT devices, I was able to add the bridge to HomeKit app

**Comment by RichW02** [comment]
I have a similar problem, but with 2 TV's.  Homebridge is working ok on a new Pi, I just installed v1.5 of  the SmartThings plugin, one TV connected ok, second gave an error message saying device not responding, even though the smartthings App can still see and control both.  

Is the a TV compatibility list somewhere? or a helpful hints list somewhere?

Sorry if I'm a bit vague, I new at this, only got the RPi yesterday afternoon and it the first time I tried anything like this............

Thanks.

**Comment by coryabooth** [comment]
> Is the a TV compatibility list somewhere? or a helpful hints list somewhere?

Couple of points.

This plugin surfaces devices that work correctly in SmartThings.
If you have your TV in Smart Things - first test if it is working correctly in Smart Things App.
If it's not working there, it won't work in the bridge - as this bridge only passes the commands from the UI to SmartThings.

TVs generally don't need a bridge.  Most TVs already have "HomeKit" built-in, especially if using something like a Roku or Apple TV.  In this case, I would configure this bridge to "ignore" the SmartThings TV(s) and simply perform the Apple HomeKit connection directly on the TV.  In this way, you are using this plugin for light switches and other Z-Wave/Zigbee devices - but using Apple Homekit directly for those devices that are compatible - another example Ecobee Themostats.

**Comment by iklein99** [comment]
The plugin doesn't offer any specific value for TVs other than on and off at the moment.  If enough people want the TV integration, I'll see what can be done.

**Comment by RichW02** [comment]
Thanks for you time and the information. I’m happy to support with a donation, what amount do you consider reasonable.  I’m retired, so have to watch my budget, so please don’t be offended by my response. Speaking of changes, how about a sleep mode to my air purifier,  that mode is good at night to keep the noise down, but currently can’t be automated. Thanks he’s for your help and great software. Regards,On 4 Feb 2023, at 12:57 am, iklein99 ***@***.***> wrote:﻿
The plugin doesn't offer any specific value for TVs other than on and off at the moment.  If enough people want the TV integration, I'll see what can be done.

**Comment by RichW02** [comment]
My TV’s are both Samsung one about 2 yrs the other older.  They both work in SmartThings ok, the older one is ok except for waking up, but both respond to channels, volumes etc. SmartThings, which I assume run in the newer TV, also relays the data to Google Home, that also works.I was trying to get rid of GHome but couldn’t figure out how to go straight from the TV to HomeKit, but Samsung aren’t particularly helpful.  Thanks for your help and time in responding to my questions. Regards,On 4 Feb 2023, at 12:52 am, coryabooth ***@***.***> wrote:﻿

Is the a TV compatibility list somewhere? or a helpful hints list somewhere?

Couple of points.
This plugin surfaces devices that work correctly in SmartThings.
If you have your TV in Smart Things - first test if it is working correctly in Smart Things App.
If it's not working there, it won't work in the bridge - as this bridge only passes the commands from the UI to SmartThings.
TVs generally don't need a bridge.  Most TVs already have "HomeKit" built-in, especially if using something like a Roku or Apple TV.  In this case, I would configure this bridge to "ignore" the SmartThings TV(s) and simply perform the Apple HomeKit connection directly on the TV.  In this way, you are using this plugin for light switches and other Z-Wave/Zigbee devices - but using Apple Homekit directly for those devices that are compatible - another example Ecobee Themostats.
