### ISSUE TITLE
Tamper Alert for Schlage door locks

### ISSUE THREAD

**Issue by carterdacat** [iklein99/homebridge-smartthings#135]
First off, thank you for this amazing plugin, works stunningly. Schlage locks have a "tamper alert" feature, and is present with history on the ST app would be really nice to have (there also is a Vacation move, and alarm, and tamper sensitivity sliders but if that's too much that's too much). Thank you so much!

**Comment by iklein99** [comment]
I'll look into it when I get a chance.

**Comment by iklein99** [comment]
There is no way to add a tamper alert to a lock in Homebridge, unfortunately.
