### ISSUE TITLE
Plug in constantly restarting

### ISSUE THREAD

**Issue by balboafer** [iklein99/homebridge-smartthings#139]
Hi!
I've just installed the plug in today, configured it as a child bridge, and I was amazed that every device in my SmartThings hub appeared almost instantly, and they were operating normally at the beginning, but after 10 minutes or so, it began to restart every 5 seconds. I've tried to check the logs, and they mention a lot of errors. the thing is first, I need help filtering the logs for the plug in only, and then solve it, of course! I'm a newbie in HB so please, be patient.
Thank you in advance.

**Comment by balboafer** [comment]
I think I partially solved the issue by filtering the options and leaving only those regarding devices, scenes, apps and scenes. I'll keep watching its behavior.

**Comment by iklein99** [comment]
I just released a webhook service which replaces the constant polling with events from SmartThings.  This should resolve any errors like that.
