### ISSUE TITLE
Issue with Webhook and adding blinds

### ISSUE THREAD

**Issue by JustWsPlease** [iklein99/homebridge-smartthings#144]
I just subscribed to the web service and everything works fine except adding blinds. When I go to add even just 1 blind I get the error "Something went wrong. Please try to install the SmartApp again". 

![IMG_4776](https://user-images.githubusercontent.com/101517808/221406037-ae5e5273-2c65-494e-a57a-0ae0249eb77a.jpeg)

**Comment by JustWsPlease** [comment]
Ok, so with blinds, I can add them 1 or 2 at a time but I have to wait about 5 to 10 min before I can add another 1 or 2. I have about 10 blinds so I'm still adding them now.

**Comment by iklein99** [comment]
Unfortunately I don’ t have blinds so it is tough for me to test.  I’ll have to take a look at that.  Thanks for letting me know.

**Comment by iklein99** [comment]
This issue was created by a SmartThings limit around device subscriptions.  I've fixed this issue.  Let me know if it happens again.
