### ISSUE TITLE
Webhook Delay?

### ISSUE THREAD

**Issue by coryabooth** [iklein99/homebridge-smartthings#147]
I have been noticing an odd behavior and wondering if it is just s fluke or if it's related to the Webhook change.

Recently I made the shift from polling to webhook.
Due to the device limits, I had a bit of a struggle completing the shift.
However, as far as I know, I am good to go.

But I have noticed some odd behavior - especially with my door locks.
I will receive notices that a door was unlocked or locked hours after I know that door was opened.

This morning I noticed I immediately got an alert my door was unlocked when I opened the Homebridge and navigated to the Accessories page.  However that door was last opened an hour prior.

I don't really have any other "alerts" configured, I'll try testing with other devices....
Functionality in the "Home" app seems perfectly fine.

This, if its an issue, would seem to impact devices where under "Settings" and "Status and Notifications" -> "Activity Notifications" has been set.

**Comment by iklein99** [comment]
Put homebridge into debug mode.  You can see incoming events from the web hook service.  Go and unlock a door and see if you get the event showing in the logs.

**Comment by iklein99** [comment]
I found an issue for people that did the SmartApp install more than once.  If you did, you may not have been receiveing events.  That should be fixed now.
