### ISSUE TITLE
Switches (TVs) not working anymore but did work last week - no changes to config

### ISSUE THREAD

**Issue by gradyhouston** [iklein99/homebridge-smartthings#148]
**Describe The Bug:**
2 of 3 Samsung TVs not responding when they had worked after install

**To Reproduce:**
Just use Siri or Home App or Homebridge UI to turn on TVs and then nothing happens

**Expected behavior:**
Use Home App or Siri to turn on TVs that previously responded to the plugin

**Logs:**

[10/03/2023, 12:56:50] [Smartthings Plug (IK)] Received setSwitchState(true) event for Basement Gaming TV - Samsung Q60 Series (65)
[10/03/2023, 12:56:50] [Smartthings Plug (IK)] on failed for Basement Gaming TV - Samsung Q60 Series (65): AxiosError: Request failed with status code 409
[10/03/2023, 12:56:50] [Smartthings Plug (IK)] Command failed for Basement Gaming TV - Samsung Q60 Series (65)

[10/03/2023, 13:11:47] [Smartthings Plug (IK)] Received response from webhook {"timeout":true,"events":[]}
[10/03/2023, 13:11:47] [Smartthings Plug (IK)] Posting request to web hook

**Plugin Config:**

```
        {
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1",
            "AccessToken": "XXX",
            "WebhookToken": "XXX",
            "GarageDoorMaxPoll": 0,
            "PollLocksSeconds": 0,
            "PollDoorsSeconds": 0,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 15,
            "IgnoreLocations": [
                "Ignored Room",
                "My location 2"
            ],
            "IgnoreDevices": [
                "XXX",
                "XXX",
                "XXX"
            ],
            "platform": "HomeBridgeSmartThings"
        }
```

**Screenshots:**

**Environment:**

* Plugin - **v1.5.1**:
* Node - **v1.6.0**:
* Homebridge - **v16.16.0**:
* NPM - **8.11.0**:
* OS - **DietPi**:

**Comment by iklein99** [comment]
It indicates that SmartThings says that turning it on would conflict with the devices current state.  

This isn’t something I can fix with the plugin as it is doing what it is being told which is set the switch state to “on”.

Try restarting homebridge or maybe even your hub.



Also try controlling the device with the SmartThigns app and see what happens there.

**Comment by gradyhouston** [comment]
Ah, I see. Weird issue on my end. Sorry about that. I thought I had checked everything before coming here.
