### ISSUE TITLE
Lost lights switches and duplication of existing switches with 1.5.2 update

### ISSUE THREAD

**Issue by drpimples** [iklein99/homebridge-smartthings#153]
The latest 1.5.2 update nuked a lot of my z-wave lights and added switches with duplicate names.

**Comment by drpimples** [comment]
Hmm.  The missing lights were actually removed from the Home View and when I choose the light from the room view and select "Show as Separate Tiles" the redundant switch disappears and the device is once again back on the Home View.

**Comment by iklein99** [comment]
The update supports multi components whereas before it would only load capabilities from the "main" component.  That and support for buttons is the only change made. 

I assume you are good now?  Can we close this?

**Comment by drpimples** [comment]
Yes.  Once I separated the multifunction from the light it’s behaving again.  Thanks.
