### ISSUE TITLE
This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all

### ISSUE THREAD

**Issue by home-automate** [iklein99/homebridge-smartthings#182]
**Describe The Bug:**
I am getting a lot of "This plugin slows down Homebridge messages. I realize the is another method of using WebHook, but wondering if this is just something that can be fixed. I ran into this issue with the Xfinity Home plug in and it was fixed there.

not sure if the plugin code can return the callback() instantly, and call [characteristic.updateValue](https://developers.homebridge.io/#/api/characteristics#characteristicupdatevalue) once the action has completed.

**To Reproduce:**
1. Install homebridge-smartthings plug-in
2. only use Access Token
3. I am using only 3 devices attached to the Smartthings 
4. examine the logfile and observe the messages that this plugin slows down HomeBridge

**Expected behavior:**
No logs littered with messages indicating it slowing down Homebridge

**Logs:**
[28/06/2023, 18:02:29] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

**Plugin Config:**
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "xxxxxxxxxxxxx"
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 5,
            "PollDoorsSeconds": 0,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 5,
            "PollWindowShadesSeconds": 0,
            "IgnoreDevices": [
               ],
            "platform": "HomeBridgeSmartThings"
**Screenshots:**

**Environment:**

* **Plugin Version**: v1.5.10
* **Homebridge Version**: Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 9FDA)
* **Node.js Version**: [v18.16.0]
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by iklein99** [comment]
You can reduce the amount of polling by changing the various settings.  That may help.

**Comment by jkal4712** [comment]
I have the same error message. It looks to be related to the smart bulbs and changing colors or brightness.  Can you elaborate more on what various settings to change?

**Comment by iklein99** [comment]
Try PollSwitchesAndLightsSeconds".  Change it to 10 or something.  The issue is with all of the polling, it can slow down the responses.  Depending upon how many devices you have, you may need to increase the polling interval (time between checks) to reduce the amount of polling.  Or sign up for the webhook service to eliminate the polling.

**Comment by jkal4712** [comment]
Looks like it is already set to 10.  I am not familiar with the webhook service? Where can I find out more information about that?  I do have a lot of devices connected. 

<img width="314" alt="Screenshot 2023-07-25 at 8 40 38 AM" src="https://github.com/iklein99/homebridge-smartthings/assets/140521108/d8cb5946-64f9-49f7-86f5-ee5820d30bac">

**Comment by iklein99** [comment]
You can find that here:  https://github.com/iklein99/homebridge-smartthings/discussions/141
