### ISSUE TITLE
Blinds not show on Apple Home

### ISSUE THREAD

**Issue by SUPA-Nicholas** [iklein99/homebridge-smartthings#185]
Blinds is not showing on Apple Home. However, all the lighting accessories is working well

Log:
[Smartthings Plug (IK)] Restoring existing accessory from cache: Spotlight
[Smartthings Plug (IK)] Restoring existing accessory from cache: LED
[Smartthings Plug (IK)] Restoring existing accessory from cache: Pendant
[Smartthings Plug (IK)] Restoring existing accessory from cache: Downlights
[Smartthings Plug (IK)] Restoring existing accessory from cache: LED

From the Homebridge Log, seem like it only detects lighting accessories

Config:
"name": "Smartthings Plug (IK)",
"BaseURL": "https://api.smartthings.com/v1/",
"AccessToken": "",
"GarageDoorMaxPoll": 40,
"PollLocksSeconds": 10,
"PollDoorsSeconds": 10,
"PollSensorsSeconds": 5,
"PollSwitchesAndLightsSeconds": 10,
"PollWindowShadesSeconds": 20,
"platform": "HomeBridgeSmartThings"

Environment:
Plugin Version: 1.5.10
Homebridge Version: 1.6.1
Node.js Version: 16.15.0
NPM Version: Can't find it
Operating System: Raspbian

**Comment by SUPA-Nicholas** [comment]
The driver for the blind:
Name: Zigbee Window Treatment
Description: SmartThings driver for Zigbee window treatment devices
Developer: SmartThings
Support Information: Https://support.smartthings.com
Version: 2023-06-13T18:57:36.061164804

**Comment by iklein99** [comment]
Thanks for the information.  I did find the issue and will get it fixed.  I'll be publishing a new version soon.

**Comment by iklein99** [comment]
This should be fixed in version 1.5.11.
