### ISSUE TITLE
Re-register unregistered device?

### ISSUE THREAD

**Issue by dougperx** [iklein99/homebridge-smartthings#196]
I accidentally deleted a device in SmartThings and it unregistered in homebridge.  I re-added it to SmartThings but I can't seem to trigger it to re-register -- is there a way to trigger the plugin to re-register a device?

**Comment by coryabooth** [comment]
It's probably cached. Click the menu icon top right of Homebridge and search for cached accessory.

**Comment by dougperx** [comment]
I'm on Hoobs so I didn't have that option but I cleared the cache and that seemed to do it, thank you!
