### ISSUE TITLE
Boiler error

### ISSUE THREAD

**Issue by ripe-avocado** [iklein99/homebridge-smartthings#197]
The boiler is marked with a thermometer, only switches and temperature indicators are available, and temperature control is not possible.

**Comment by iklein99** [comment]
@ripe-avocado , please follow the directions in the linked document to send me the detailed logs.  I need to see the information about the device at startup.  Let me know the name of that device.

[Instructions for Producing a Detailed Log.pdf](https://github.com/iklein99/homebridge-smartthings/files/12837873/Instructions.for.Producing.a.Detailed.Log.pdf)
