### ISSUE TITLE
Ignore Devices

### ISSUE THREAD

**Issue by matrix2669** [iklein99/homebridge-smartthings#2]
Is there anyway to have it ignore certain devices? I have a hub at my office and my home and it is adding all the devices from both.

**Comment by iklein99** [comment]
Thanks for the suggestion.  I can add that in on. my next build.  Look out for it in the next couple of weeks.

**Comment by iklein99** [comment]
Version 1.1.1 has been added.  You can specify locations now to ignore.  Just add the location for your office in that list.  All of those devices will be removed from homebridge.  Let me know how you make out
