### ISSUE TITLE
Add Lock Contact Sensors

### ISSUE THREAD

**Issue by chevellebro1** [iklein99/homebridge-smartthings#20]
Is it possible to add the contact sensor capability into the lock settings?

**Comment by veonua** [comment]
what is the use case? does your lock have an additional sensor?

**Comment by chevellebro1** [comment]
my lock has a contact sensor on the door frame to notify me if the door is left open. i also use this to trigger automations such as “if door opens and it’s night, turn on the porch light”

**Comment by iklein99** [comment]
Chevellebro1, I'll look into this, but your pull request would not have worked.  Please refrain from doing that going forward.  Now one question, is the contact sensor a separate device on your smartthings network, or is it a capability of the lock in smartthings?

**Comment by iklein99** [comment]
Supported in 1.4.3.
