### ISSUE TITLE
Homebridge in restarting loop

### ISSUE THREAD

**Issue by mwporter11** [iklein99/homebridge-smartthings#202]
**Describe The Bug:**
I needed to update my node.js and ended up rebuilding by entire homebridge from scratch.  Once I installed the smartthings plug-in, I get an error and homebridge restarts.  It's in a constant loop.  Was working before I updated everything.

**To Reproduce:**
Not sure as this is a fresh install

**Expected behavior:**
I would expect the plug-in  to bring in my smartthings accessories into homebridge to control via homekit

**Logs:**

[8/16/2023, 7:13:16 PM] [homebridge-smartthings-ik] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 74.3 exceeded maximum of 38. See https://homebridge.io/w/JtMGR for more info.
[8/16/2023, 7:13:16 PM] Error: HAP Status Error: -70402
    at new HapStatusError (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:17:5)
    at /homebridge/node_modules/homebridge-smartthings-ik/src/services/thermostatService.ts:205:18
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[8/16/2023, 7:13:16 PM] Got SIGTERM, shutting down Homebridge...

**Plugin Config:**

{
    "name": "Smartthings Plug (IK)",
    "BaseURL": "https://api.smartthings.com/v1/",
    "AccessToken": "xxxxxxxxx",
    "GarageDoorMaxPoll": 40,
    "PollLocksSeconds": 10,
    "PollDoorsSeconds": 10,
    "PollSensorsSeconds": 5,
    "PollSwitchesAndLightsSeconds": 10,
    "PollWindowShadesSeconds": 20,
    "ExposeHumiditySensorForAirConditioners": false,
    "platform": "HomeBridgeSmartThings"
}

**Screenshots:**

**Environment:**

WD Ultra EX2 NAS

* **Plugin Version**: 1.5.13
* **Homebridge Version**: 22.04
* **Node.js Version**: v18.16.0
* **NPM Version**: 
* **Operating System**: Docker

**Comment by coryabooth** [comment]
In the future, you don't have to rebuild to update Node.  Just click the hamburger icon and Terminal.  Instructions are on the screen

**Comment by mwporter11** [comment]
> In the future, you don't have to rebuild to update Node. Just click the hamburger icon and Terminal. Instructions are on the screen

Thank you.  I needed to update my portainer version as well, but pretty sure I did it the hard way.  I appreciate the info for next time as I didn't realize it was that easy in Terminal...

**Comment by iklein99** [comment]
Follow the instructions in this document and send me the detailed logs.

[Instructions for Producing a Detailed Log.pdf](https://github.com/iklein99/homebridge-smartthings/files/12369078/Instructions.for.Producing.a.Detailed.Log.pdf)

**Comment by mwporter11** [comment]
Fixed!  @iklein99 reviewed the code and determined it was an issue with a ZEN brand z-wave thermostat.  Once I ignored those in the plug-in, it all started working as it should.

Big THANKS for troubleshooting it so quickly!
