### ISSUE TITLE
Battery Status

### ISSUE THREAD

**Issue by greztaylor** [iklein99/homebridge-smartthings#205]
Is there a way to hide the battery status of devices using the plugin?

I have 2 x Yale Conexis L1 Smart Locks that continually report a love battery despite that not being the case and would love to hide the alerts in the Apple Home app.

Thanks in advance.

**Comment by iklein99** [comment]
Not at this time.

Are you referring to the warning messages in the Homebridge logs, or what is shown in the Home app?

**Comment by greztaylor** [comment]
Primarily in the Home app but the logs are repeatedly saying Low Battery for both locks too🪫

**Comment by iklein99** [comment]
I’ll look into it,

**Comment by iklein99** [comment]
Latest release will stop showing warnings in the logs for low battery.  However, I didn't change the way the plugin works.  If there is a battery capability in the smartthings device, and it shows below 30%, the plugin will report that as low.  I'd suggest contacting the developer of the smart lock device driver about this.
