### ISSUE TITLE
Devices to Ignore & Device Limit

### ISSUE THREAD

**Issue by therapcat** [iklein99/homebridge-smartthings#214]
**Describe The Bug:**
There is a limit of 149 devices even if devices are listed in devices to ignore. This should be fixed. Also the devices to ignore still show up in HomeKit/Hoobs.

**To Reproduce:**
connect to Smartthings and the logs will show the limit. Ignored devices are 

**Expected behavior:**
Expected to only have a few devices shown to HomeKit, but it is duplicating all of the Hue lights that are in Smartthings and also in HomeKit natively. I've listed the lights to ignore but they still show up and it cuts off the ability to add my other ST devices that aren't hue bulbs. 

**Logs:**
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Inside door
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: House Fan
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Guest Room door
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Guest Motion Wall Switch
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Dining Wall
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Enerwave RSM2-Plus
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Office Motion
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Nikki Toilet Relay
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Garage CFL
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Back window
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Toilet Paddle 1
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Guest Room
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Button
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Toilet Paddle
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: office
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Garage Motion
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Shower
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Garage Door Switch
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Nikki Toilet Fan
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Preheat Spa
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Restoring existing accessory from cache: Black Light
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)Registering new accessory: Entryway Motion
9/7/2023, 9:39:27 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not load devices from Smartthings: Error: Cannot Bridge more than 149 Accessories.  Check your configuration
9/7/2023, 9:39:30 PMSmartThings Ik BridgeERROR[SmartThings Ik Bridge C963@Nikki Toilet Relay@@Brightness] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
9/7/2023, 9:39:31 PMHue BridgeLoaded plugin 'homebridge-hue'
9/7/2023, 9:39:31 PMHue BridgeLoading 1 platforms...
9/7/2023, 9:39:31 PMHue BridgeHuehomebridge-hue v0.13.60, node v14.19.1, homebridge v1.3.5
9/7/2023, 9:39:31 PMHue BridgeHueWARNINGwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
9/7/2023, 9:39:31 PMHue BridgeHueHue 2: Signify Netherlands B.V. BSB002 bridge v1959194030, api v1.59.0
9/7/2023, 9:39:31 PMHue BridgeHueWARNINGHue 2: warning: not using recommended Hue bridge api version 1.56.0
9/7/2023, 9:39:31 PMSmartThings Ik BridgeERROR[SmartThings Ik Bridge C963@Nikki Toilet Fan@@Brightness] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
9/7/2023, 9:39:32 PMHue BridgeHueHue 2: 3 accessories
9/7/2023, 9:39:32 PMHue BridgeHuemasked debug info dumped to /var/lib/hoobs/huebridge/homebridge-hue.json.gz
9/7/2023, 9:39:32 PMHue BridgeHueHue 2: 2 services
9/7/2023, 9:39:32 PMHue BridgeBridge is running on port 51836.
9/7/2023, 9:39:32 PMHue BridgeHueHue 2: event stream connected to https://192.168.1.25/eventstream/clip/v2
9/7/2023, 9:39:32 PMHue BridgeHueWARNINGwarning: latest version: homebridge-hue v0.13.66
9/7/2023, 9:59:54 PMHue BridgeHueNeon Sign: homekit on changed from true to false
9/7/2023, 9:59:54 PMHue BridgeHueCouch Bar: homekit on changed from true to false
9/7/2023, 9:59:55 PMScreenlogic BridgeERROR[Screenlogic Bridge 960D@Pool Light@@On] SET handler returned write response value, though the characteristic doesn't support write response
9/7/2023, 9:59:55 PMScreenlogic BridgeERROR[Screenlogic Bridge 960D@Spa Light@@On] SET handler returned write response value, though the characteristic doesn't support write response
9/7/2023, 9:59:55 PMScreenlogic BridgeERROR[Screenlogic Bridge 960D@Laminar@@On] SET handler returned write response value, though the characteristic doesn't support write response
9/7/2023, 9:59:55 PMScreenlogic BridgeERROR[Screenlogic Bridge 960D@Deck Light@@On] SET handler returned write response value, though the characteristic doesn't support write response
9/7/2023, 10:01:38 PMDyson BridgeDysonPureCoolPlatformE4D-US-MJA0926A - set JetFocus to false: {"fdir":"OFF","ffoc":"OFF"}
9/7/2023, 10:01:38 PMDyson BridgeDysonPureCoolPlatformE4D-US-MJA0926A - set ContinuousMonitoring to false: {"rhtm":"OFF","fmod":"OFF"}
9/7/2023, 10:01:38 PMDyson BridgeDysonPureCoolPlatformE4D-US-MJA0926A - set NightMode to false: {"nmod":"OFF"}
9/7/2023, 10:13:04 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:04 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:04 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORGuest Room is offline
9/7/2023, 10:13:04 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:04 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:04 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:04 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:04 PMSmartThings Ik BridgeSmartthings Plug (IK)Back window is offline
9/7/2023, 10:13:05 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:05 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:05 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:05 PMSmartThings Ik BridgeERROR[SmartThings Ik Bridge C963@Nikki Toilet Fan@@Brightness] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
9/7/2023, 10:13:06 PMSmartThings Ik BridgeERROR[SmartThings Ik Bridge C963@Nikki Toilet Relay@@Brightness] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
9/7/2023, 10:13:34 PMSmartThings Ik BridgeSmartthings Plug (IK)Back window is offline
9/7/2023, 10:13:34 PMSmartThings Ik BridgeSmartthings Plug (IK)Back window is offline
9/7/2023, 10:13:34 PMSmartThings Ik BridgeSmartthings Plug (IK)Back window is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORGuest Room is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:35 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:35 PMSmartThings Ik BridgeERROR[SmartThings Ik Bridge C963@Nikki Toilet Relay@@Brightness] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
9/7/2023, 10:13:36 PMSmartThings Ik BridgeERROR[SmartThings Ik Bridge C963@Nikki Toilet Fan@@Brightness] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)Back window is offline
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORGuest Room is offline
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:43 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORGuest Room is offline
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)Back window is offline
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:55 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:13:56 PMSmartThings Ik BridgeERROR[SmartThings Ik Bridge C963@Nikki Toilet Relay@@Brightness] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
9/7/2023, 10:13:56 PMSmartThings Ik BridgeERROR[SmartThings Ik Bridge C963@Nikki Toilet Fan@@Brightness] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
9/7/2023, 10:14:01 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:14:01 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room door is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)Back window is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORGuest Room is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)Guest Room is offline
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/7/2023, 10:14:07 PMSmartThings Ik BridgeSmartthings Plug (IK)ERRORCould not get device status for Guest Room
9/8/2023, 10:21:39 AMDyson BridgeDysonPureCoolPlatformJ9N-US-PHA0197A - set ContinuousMonitoring to true: {"rhtm":"ON"}
9/8/2023, 10:21:39 AMDyson BridgeDysonPureCoolPlatformE4D-US-MJA0926A - set ContinuousMonitoring to true: {"rhtm":"ON"}
```

**Plugin Config:**

```json
"platform": "HomeBridgeSmartThings",
    "name": "Smartthings Plug (IK)",
    "BaseURL": "https://api.smartthings.com/v1/",
    "AccessToken": "6d162143-82ca-4a41-8e9e-de8acc944597",
    "WebhookToken": "fdfa4e30-4df5-11ee-bad4-63278b5313da",
    "GarageDoorMaxPoll": 40,
    "PollLocksSeconds": 10,
    "PollDoorsSeconds": 10,
    "PollSensorsSeconds": 5,
    "PollSwitchesAndLightsSeconds": 10,
    "PollWindowShadesSeconds": 20,
    "IgnoreDevices": [
        "Patio Up S",
        "Downlight South",
        "Smart Outdoor Plug",
        "LightStrips Left",
        "Headboard South",
        "Nikki 2",
        "left fence",
        "Garage Right",
        "Front Center",
        "Patio Strip",
        "Living Room2",
        "Entryway",
        "Globe Lamp",
        "Hanging Lights",
        "Back Door L",
        "Front Door",
        "Dining 3",
        "Nikki's Nightlight",
        "Bench Left",
        "Garage Strip",
        "Chaise",
        "Headboard North",
        "LIFX right",
        "Smart Outdoor Plug",
        "Toilet",
        "Dining 1",
        "Side Window",
        "bulb tree",
        "Windows Open",
        "Hue outdoor spot 3",
        "Buddy Pee Sensor",
        "Nikki's Room",
        "Dining 4",
        "nikki bathroom",
        "nikki bathroom 1",
        "Front Porch",
        "Motorcycle",
        "Tesla left",
        "Switch 2",
        "Hue outdoor spot 3",
        "Hue outdoor spot 1",
        "GE Plug-in Outdoor Switch",
        "Patio Strip 2",
        "Downlight North",
        "Bedtime",
        "Camper Under",
        "Kitchen 4",
        "Nikki Toilet Paddle 1",
        "Shower Right",
        "Aeon Labs Siren (Gen 5)",
        "Garage Entry",
        "Fridge",
        "Kitchen 5",
        "Switch 1",
        "Bathroom Lights 1",
        "Smart Outdoor Plug",
        "LIFX left",
        "Nikki 1",
        "Front left",
        "tesla Right",
        "Switch 1",
        "iPhone",
        "Govees",
        "Sectional 1",
        "outdoor DJ lasers",
        "Front window",
        "Hall 1",
        "Nikki Toilet",
        "Bedroom Entry",
        "Corner Tree",
        "DJ2",
        "Bamboo Up",
        "Hue play Left",
        "Patio Up N",
        "Front Porch",
        "Sectional 7",
        "Porch South",
        "Porch North",
        "Switch 1",
        "Kitchen 1",
        "Kitchen 6",
        "Aux Power",
        "south fence outdoor switch",
        "Hue outdoor spot 2",
        "Dining 2",
        "Under Bed Motion",
        "Toilet Relay",
        "Table Lamp",
        "Hue bloom",
        "Nikki Window",
        "Bedroom Door",
        "Garage Left",
        "Switch 2",
        "Hue Wall Washer",
        "Sectional 5",
        "Bed Left",
        "Couch Bar",
        "Wisteria",
        "Couch Strip",
        "Shower Left",
        "Bed Gradient",
        "Laundry Room Light",
        "Master1",
        "right fence",
        "corner led floods",
        "Neon Sign",
        "Bed Right",
        "Entryway",
        "iPhone",
        "Little Garage",
        "Gradient 65",
        "Arrival Sensor",
        "Sectional 3",
        "Back Door R",
        "LightStrips Right",
        "Sectional 4",
        "Hue outdoor spot 2"
    ]
}

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Plugin Version**: 1.5.14
* **Homebridge Version**: <!-- homebridge -V -->4.0.110
* **Node.js Version**: <!-- node -v -->14.19.1
* **NPM Version**: <!-- npm -v -->
* **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by iklein99** [comment]
Closing. No response
