### ISSUE TITLE
Soundbars as receiver?

### ISSUE THREAD

**Issue by neverwalkerwan** [iklein99/homebridge-smartthings#217]
**Is your feature request related to a problem? Please describe:**
Samsung soundbar only shown as switch

**Describe the solution you'd like:**
show Samsung soundbar as receiver so we can switch sources, volume and power! That would be so cool!

Thaaaanks

**Comment by iklein99** [comment]
@neverwalkerwan , please follow the directions in the following link and send me the detailed logs when you start up homebridge.  I have to see what capabiliites the soundbar advertises. 
[Instructions for Producing a Detailed Log.pdf](https://github.com/iklein99/homebridge-smartthings/files/12706614/Instructions.for.Producing.a.Detailed.Log.pdf)

**Comment by iklein99** [comment]
Closing due to lack of response.
