### ISSUE TITLE
Hoobs pulling in all devices from Smarthings

### ISSUE THREAD

**Issue by pman930x** [iklein99/homebridge-smartthings#238]
**Describe Your Problem:**
I just installed Smartthings into hoobs, and there is no way to exclude devices.  For example HUE and Lutron work with HOmekit, so I dont need to bring them over from smart things.  The function better with the Lutron or HUE integration.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by iklein99** [comment]
There is a config setting, "IgnoreDevices" which holds a list of the devices you want to ignore.

**Comment by pman930x** [comment]
Thanks! Oh I see its under the “Cache” in HOOBS there is not “Ignore devices” or config settings in HOOBS

 

Best regards,

 

Peter Masih

**Comment by pman930x** [comment]
Wait the cache just removes from the room.  I found the configuration section on hoobs but there is no way to identify and remove devices.

 

Please advise, I have attacged screen shots.

 

Thanks

 

Best regards,

 

Peter Masih

 

From: ***@***.*** ***@***.***> 
Sent: Sunday, November 26, 2023 12:42 PM
To: 'iklein99/homebridge-smartthings' ***@***.***>; 'iklein99/homebridge-smartthings' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [iklein99/homebridge-smartthings] Hoobs pulling in all devices from Smarthings (Issue #238)

 

Thanks! Oh I see its under the “Cache” in HOOBS there is not “Ignore devices” or config settings in HOOBS

 

Best regards,

 

Peter Masih

**Comment by iklein99** [comment]
Are you still having this issue?  There is a setting for the plugin called IgnoreDevices.  Use that.

**Comment by pman930x** [comment]
I don’t see this in the hoobs. When I am at my office I will send u screen shots of what I see. Thanks Best regards,Peter MasihOn Feb 23, 2024, at 8:26 AM, iklein99 ***@***.***> wrote:﻿
Are you still having this issue?  There is a setting for the plugin called IgnoreDevices.  Use that.

**Comment by pman930x** [comment]
Hi there:

 

Sorry for the delay.

 

Please take a look, no where under the hoobs GUI for your app do I see “ignore devices”

 

I have a host of Smart devices that integrate with HomeKit, and a bunch that don’t, everything I have is on Smarthings.  But if things natively work with Apple  Homekit  I prefer to have them do so.

 

Right now I am just hiding the devices on my apple Home app, but they still count as the devices that are on etc.

 

Anything you can do would help greatly.

 

Have a good evening.

 

Best regards,

 

Peter Masih
