### ISSUE TITLE
Lock tamper status

### ISSUE THREAD

**Issue by carterdacat** [iklein99/homebridge-smartthings#240]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
A sensor or some way to see the tamper status of the lock, so I can trigger the security system as an automation.

**Describe alternatives you've considered:**
I don't know any other alternatives

**Additional context:**
None

**Comment by iklein99** [comment]
Tamper detections is only supported in these devices according to the homebridge documentation:

[Air Quality Sensor](https://developers.homebridge.io/#/service/AirQualitySensor)
[Carbon Dioxide Sensor](https://developers.homebridge.io/#/service/CarbonDioxideSensor)
[Carbon Monoxide Sensor](https://developers.homebridge.io/#/service/CarbonMonoxideSensor)
[Contact Sensor](https://developers.homebridge.io/#/service/ContactSensor)
[Humidity Sensor](https://developers.homebridge.io/#/service/HumiditySensor)
[Leak Sensor](https://developers.homebridge.io/#/service/LeakSensor)
[Light Sensor](https://developers.homebridge.io/#/service/LightSensor)
[Motion Sensor](https://developers.homebridge.io/#/service/MotionSensor)
[Occupancy Sensor](https://developers.homebridge.io/#/service/OccupancySensor)
[Security System](https://developers.homebridge.io/#/service/SecuritySystem)
[Smoke Sensor](https://developers.homebridge.io/#/service/SmokeSensor)
[Temperature Sensor](https://developers.homebridge.io/#/service/TemperatureSensor)

The lock service doesn't support it.
