### ISSUE TITLE
Frient Power Meter

### ISSUE THREAD

**Issue by matteobaraldi80** [iklein99/homebridge-smartthings#243]
**Describe The Bug:**
The Power meter is loaded correctly but the property loaded is only 1, can see olny the battery charge of the device and not the Power misured by itself.

In my smartthings panel i can see theese properties : 
![image](https://github.com/iklein99/homebridge-smartthings/assets/154685126/70813cbe-e70a-4cbe-af83-ffd839195d43)

seems that the plugin load only the first capability but the last one is the real information that needs

thanks for any hint

* **Plugin Version**: 
v1.5.20
* **Homebridge Version**: 1.61

* **Operating System**: hb-service

**Comment by iklein99** [comment]
Unfortunately, Homekit does not have service types that match power meters or anything like them.
