### ISSUE TITLE
Does this support sensors?

### ISSUE THREAD

**Issue by sebastiangoldstein** [iklein99/homebridge-smartthings#25]
Does this support sensors?
I need to replace my aging smart things plugin which will not work after September 30 when the Groovie IDE is pulled. 

Looking specifically for support of zwave and zigbee:
Motion, contact, temperature, and leak sensors. 

Thank you in advance.

**Comment by iklein99** [comment]
I just released a version that supports motion sensors.  I am working on other sensors now so soon.

**Comment by sebastiangoldstein** [comment]
Wonderful - Thank you for your awesome work!

**Comment by Acalade** [comment]
Since v1.3.1, my motion sensors show triggered constantly.  I have both Smartthings Motion Sensors, and aeotec multisensor 6s.

**Comment by iklein99** [comment]
Yeah, sorry about that.  Small bug.   Fixed in 1.3.2.

**Comment by cms365** [comment]
Also looking forward to Open/Close sensors. Fantastic work! Thank you!

**Comment by Acalade** [comment]
Thank you for the fast update.  I am also looking forward to Open/Close sensors. also hoping Temperature sensors are coming as well.

**Comment by sebastiangoldstein** [comment]
@iklein99 Any status on Contact Sensors (doors and windows). Really looking forward to transitioning over to your new plug- in but I have too many automations that are triggered off of contact sensors, so I'm waiting for the plug-in to support them. Thanks!

**Comment by iklein99** [comment]
I'll get to that next.

**Comment by firstspencer** [comment]
Hi Klein,My ST doors and windows are showing as switches in HomeKit even though they’re configured at “contacts” in ST. See below 2 images. The first is taken from ST and the 2nd is from HomeKit. Also, only 2 of 7 contacts are coming over into HomeKit. The plugin misses the rest of them. The others that aren't coming over are shown in the 3rd image. Thanks again for your help. It’s really appreciated. Darrell SpencerSent from my iPhoneOn Oct 6, 2022, at 1:41 PM, iklein99 ***@***.***> wrote:﻿
I'll get to that next.

**Comment by iklein99** [comment]
Contact sensors have been added in version 1.4.3.  @firstspencer I don't know why your doors and windows look like switched before this release unless the devices are carrying a 'switch' category.  Try this version, and if the problem still occurs, then clear your logs in the Homebridge settings screen, turn debug on and restart.  After about 30 seconds, you can shut debug off.  Send me the logs you get and restart homebridge.  Send the logs to me at iklein99@comcast.net.

**Comment by iklein99** [comment]
Probably your sensor isn't reporting a category that is recognized by the plugin.  I'm working on a change right now to support multi service accessories and that should resolve this issue.

**Comment by cirrusflyer** [comment]
Great plugin!  Look forward to the contact sensors with ST Multipurpose.

**Comment by iklein99** [comment]
I'm just finishing up my rework to support accessories with multiple services.  Will be released soon.

**Comment by cirrusflyer** [comment]
I ended up trying the beta and it's working pretty well with ST Multipurpose.  Any chance you can support smoke detectors?  The old Smartthings integration allowed for these.  And other types of contact sensors like "wireless tags".

Thanks!

**Comment by iklein99** [comment]
Smoke detector support in release 1.4.11
