### ISSUE TITLE
constant calls to api.smartthings.com

### ISSUE THREAD

**Issue by sjensen009** [iklein99/homebridge-smartthings#250]
**Describe The Bug:**
this seems to have started within the last few days, in a 24 hour period, I’m seeing ~115k calls to api.smartthings.com.  these are nonstop all day long. I’m not necessarily saying anything is wrong but in this expected?

**To Reproduce:**
 Nothing specific need to reproduce. just have the plugin running.

**Expected behavior:**
is what I’m seeing expected behavior?

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**
![IMG_1366](https://github.com/iklein99/homebridge-smartthings/assets/49462967/49f3bd92-5c9c-4d37-9885-1cca810d7a82)

**Environment:**

* **1.5.20**
* **Homebridge Version**:  homebridge 1.6.1
* **Node.js Version**:  node -v 18.2.1
* **NPM Version**: 
* **Operating System**:  Raspbian GNU/Linux Bullseye

**Comment by iklein99** [comment]
If you are NOT using the webhook service, your devices are polled all day long.  That is a call to smartthings API to find the status.  You can control how often this is done via the configuration.  By making the poll values larger, you will be polling less frequently, and updates will be slower to come into homekit.  If you do not want the polling, you can sign up for the webhook service which eliminates polling.  You can find out more at https://www.kleinstudios.net/

**Comment by sjensen009** [comment]
Oh shoot. Now that you mention the web hook service, I recall reading about that previously. Thank you for the replay.

**Comment by iklein99** [comment]
Closing - expected behavior
