### ISSUE TITLE
API Down?

### ISSUE THREAD

**Issue by coryabooth** [iklein99/homebridge-smartthings#254]
I noticed all my SmartThings went offline tonight 3/27/2024 - 10PM Central...
I haven't had any issue for several years now aside from minor tweaks - but I've never seen every device go offline

My other bridges are working (Generac / Scrypted, etc...)
Alexa integration with SmartThings is fine...
SmartThings organic connections are fine...

**Comment by coryabooth** [comment]
Looks like it's back online - disregard.

**Comment by JeffGoldner** [comment]
I had some network nonsense today when Xfnitiy went down for a short bit. Then my gateway got reset but I have recovered that and most things seem to work except for this plug-in (only plug-in on the homebridge instance). I can control things through the Smart Things app but all my automations are busted. Got a new token, restarted the child bridge ST plug-in but no joy. 

[3/28/2024, 9:16:27 PM] [Smartthings Plug (IK)] Error getting devices from Smartthings: Error: getaddrinfo EAI_AGAIN api.smartthings.com
[3/28/2024, 9:16:27 PM] [Smartthings Plug (IK)] Could not load devices from Smartthings: undefined.  Check your configuration

**Comment by JeffGoldner** [comment]
False alarm. The issue was triggered by a spurious Xfinity change to my gateway (which I had to revert) which prevented DNS resolution. My QNAP NAS needed a reboot to clear up the leftover issues.

**Comment by coryabooth** [comment]
To add...
To fully get all my devices back to normal I had to disable:
IGMP Snooping 
Multicast and Broadcast Control

**Comment by coryabooth** [comment]
To fully get all my devices back to normal I had to disable:
IGMP Snooping
Multicast and Broadcast Control
