### ISSUE TITLE
Lights and Switches Not Updating Status

### ISSUE THREAD

**Issue by kevinjonsutton** [iklein99/homebridge-smartthings#26]
First off, thank you very much for all your hard work on this plugin. I'm having a couple of issues with switches and lights.

1. If I turn on/off a light switch via a physical switch in my house, Alexa, or the smartThings app the status does not update in the HomeKit app. The only way to get it to update is to either force quit the app or use the app switcher to switch to another app and then back to the HomeKit app. 

2. I have some virtual switches that were pulled in through the plugin to automate the STHM. I'm using the homebridge security system plugin so it turns on the alarm. The problem is that since it is not updating right away the automation won't work. 

3. On iOS 16, the new widgets on the lock screen are not working correctly. If I turn 30 lights on at my house and then later turn them all off the widget will still show 30 lights on. The only way I can get it to update correctly is to turn a single light on and then off. 

I'm assuming all of these issues are because the plugin is not updating the status right away. I'm noticing this on iOS 15.7 as well as iOS 16. I'm wondering if there is a way to speed up the updating status time for lights/switches or maybe add a polling feature like you have for garage doors and locks because those seem to update instantly on my device in HomeKit. Thanks again for all of your work on this plugin!

**Comment by iklein99** [comment]
So, I have found that lights and switches all update every time you bring Home up on your device.  Each time you bring the app into focus, it causes Homebridge to get updates from the switches and lights and updates based on current state.  Are you not seeing that?

**Comment by kevinjonsutton** [comment]
Yes, that works. Whenever you use the app switcher to go back to the home app or open up the app for the first time if the app was closed the lights will update. 

However, if you have the app open and you turn on a specific light while looking at all of the lights it will not update the status. Looks like it only updates the status if you have the app running in the background and you switch to that app or open it from being closed. Any way to get the status to update in the background or use some sort of polling to get the status more frequently? If I have the app open and unlock a door the status shows almost instantly. Just doesn't work with lights.

Also, the home widget (iOS 16) doesn't display correctly. In this screen shot I have 13 lights turned on but it shows they are all off. They only way to get it to update correctly is to open the home app and turn another light on and then off again and then it will be reflected in the status. I have native Hue lights and the status is reflected here when they are turned on or off. Sounds like it doesn't update all the time like locks and garage doors do. Thanks for the help.

![IMG_0230](https://user-images.githubusercontent.com/45573456/190259742-d0c96660-9d15-4a6f-8bba-e21207f820f0.PNG)

**Comment by iklein99** [comment]
Switches are now polled (v1.4.1).  So they will update if their state changes outside of Homekit.  Lights will be next.

**Comment by iklein99** [comment]
Lights will now poll for on/off in 1.4.2.  Closing

**Comment by iklein99** [comment]
Yes, I can poll - the plugin does this for garage doors, locks and motion sensors.  I can add that.  I’ll let you know.
