### ISSUE TITLE
Hoobs

### ISSUE THREAD

**Issue by blaine07** [iklein99/homebridge-smartthings#27]
Pardon my total idiocracy— how can I or could I get this plugin to work in Hoobs?

**Comment by blaine07** [comment]
Ahh found it! Excellent. Hoobs says newest version is 1.2.1; in Github it says 1.3 is newest. How often is Hoobs version aligned with Github?

**Comment by iklein99** [comment]
I’m not sure why that is.  I am not using HOOBS, but have it homebridge installed on a linux box and had no problem getting the latest.  I’ll see if I can figure anything out.

**Comment by blaine07** [comment]
> I’m not sure why that is. I am not using HOOBS, but have it homebridge installed on a linux box and had no problem getting the latest. I’ll see if I can figure anything out.
> […](#)

Maybe it pulls itself to Hoobs? 

This is inside Hoobs:

![7098335E-383A-4A42-A633-8ACD3A8A0B63](https://user-images.githubusercontent.com/63940698/190632842-9e74fff1-fde8-453c-9c0d-9fec46a115ec.jpeg)
![60167AF0-50FC-4073-B9E6-1393ACD93211](https://user-images.githubusercontent.com/63940698/190632848-7742530c-495c-40bf-94d5-03f766439933.jpeg)

**Comment by iklein99** [comment]
Looks to me like someone forked my build. You aren’t pulling the right one.

Look for homebridge-smartthings-ik.  Like that.  It will show up as SmartThings Plugin.

**Comment by blaine07** [comment]
> Looks to me like someone forked my build. You aren’t pulling the right one. Look for homebridge-smartthings-ik. Like that. It will show up as SmartThings Plugin.
> […](#)

Yes that’s my issue. Joe sure how or if I can define what I want to pull in Hoobs :-(

**Comment by iklein99** [comment]
You should be able to go into the homebridge user interface and select “Plugins” from the top menu.  From there, you should be able to search for homebridge-smartthings-ik, then instal it.  Read the readme file to get the access token from smart things.
