### ISSUE TITLE
Groovy?

### ISSUE THREAD

**Issue by jplwoodward** [iklein99/homebridge-smartthings#31]
Will this plugin keep working after Groovy is discontinued?

**Comment by veonua** [comment]
yes, it is based on the new API.

**Comment by jplwoodward** [comment]
Thank you.  I see you have integrated only devices that you have, and that thermostat support has been requested.  I have a thermostat, and am a developer with limited experience extending (non-Smartthings) Homebridge plugins running my my Raspberry Pi 4.  If I can be of assistance to you, please let me know.  If you want me to attempt to add thermostat support, and would consider adding my changes to a future release, please let me know.  - John

**Comment by iklein99** [comment]
I will let you know.  I am working on refactoring my plugin so that devices can support multiple services so I would like try and limit anyone making changes.  However, if you'd be interested in helping me test, I'd be happy to loop you in.

**Comment by jplwoodward** [comment]
Yes, I am happy to help.  - John

**Comment by iklein99** [comment]
So, I'm going to close this out.  You can create a new issue to support the thermostat.  If you want, you can fork this repository and take a crack at it.  When finished, you would create a pull request that will allow me to approve the change and merge it into this code base.  But you need to make sure it is well tested as I can't test it.

**Comment by veonua** [comment]
>  But you need to make sure it is well tested as I can't test it.

could you please install the virtual thermostat from https://community.smartthings.com/t/st-edge-virtual-things-edge-driver/232875
it can help with development and tests

**Comment by jplwoodward** [comment]
I am woking on this now in my spare time.  It turns out that Smartthings and HomeKit have different models of how a thermostat works.  I am replicating the logic done in the now-obsolete tonesto plugin (homebridge-smartthings v2.3.8).  It was verified, so I am hoping it gets the HomeKit part right.  - John

**Comment by jplwoodward** [comment]
Thanks.  I am working with v1.4.4.  Is that post refactoring?  - John

**Comment by iklein99** [comment]
Yes.  That is it.

I’m now working on another refactor to allow a device to support multiple services.  So I will be making more changes.

**Comment by jplwoodward** [comment]
I have not used git, and I fear that if I fork and update as you suggest that I could do more harm than good. Below are links to 3 files:

thermostatAccessory.js — complete code to support smartthings thermostats, in the style of your accessory code
platform.js — contains minor additions to your 1.4.5 version to cause the thermostat code to be used when needed.  Each line I added has my initials — JW — on it.
config.schema.json — I added a field to specify polling seconds (your 1.4.5 version modified)

I have tested this extensively with my thermostat, and have simulated other thermostat features to test for broader compatibility.

As I mentioned before, HomeKit and SmartThings have different models of temperature units.  HomeKit shows what it implies (“Hardware Display”) are the units displayed on the actual thermostat, and allows the user to change the units. However, SmartThings does not allow commanding the thermostat to change the units.  Furthermore, regardless of what I set on my thermostat for units to display, it reports temperature to HomeKit in F, and specifies that they are F.  Another thermostat might report in C, but would tell my code and be handled properly.  Bottom line, everything functionally works, except that changing that setting has no effect.


https://thewoodwards.us/transfer/thermostatAccessory.js <https://thewoodwards.us/transfer/thermostatAccessory.js>
https://thewoodwards.us/transfer/platform.js <https://thewoodwards.us/transfer/platform.js>
https://thewoodwards.us/transfer/config.schema.json <https://thewoodwards.us/transfer/config.schema.json>

- John

**Comment by iklein99** [comment]
John,

I’ll have a look at what you did.  One issue is that the source code for the plugin in Typescript, which get precompiled into Javascript.  What you probably did was just pull the compiled javascript from the /dist folder.  I can’t use the files as you sent them because of this.

However, I’ll have a look at what you did and see how much work it will be to port into Typescript and get it properly integrated into my code.

**Comment by jplwoodward** [comment]
Yes, I added/modified them in dist. Sorry is I made more work for you.  The .ts files look identical to me.   - John

**Comment by jplwoodward** [comment]
Is 1.4.9 intended to support thermostats?  For mine, is I look in the Home app on my Mac I get:



notice ot says not responding.  If I click on accessories, it shows 3:



None actually control the thermostat, though the 60 degree and 66 degree values are correct.  - John

**Comment by veonua** [comment]
only temperature characteristic is connected. so it's more like a thermometer device now

**Comment by iklein99** [comment]
No, not yet.  It supports sensors like temp and humidity, but no control yet.
