### ISSUE TITLE
Request: Presence Sensors

### ISSUE THREAD

**Issue by kendalvandyke** [iklein99/homebridge-smartthings#32]
We're an iPhone family but I don't want to put the SmartThings app on all my kids' devices just to get presence detection because they get _everything_ else that comes with it (namely the ability to modify devices). I want to use HomeKit with HomeBridge so I can create routines in SmartThings. To do so, I've added them to my house in HomeKit with minimal permissions. Then I'm using TAustin's [vEdge Creator](https://community.smartthings.com/t/st-edge-vedge-creator-a-virtual-device-generator-for-end-users/231786) to create virtual switches and presence sensors, using HomeKit to turn a virtual switch on or off based on their presence, and a SmartThings routine to update the virtual presence sensor based on the switch.

Having extra virtual devices and automations works, albeit kludge. It would be great if your plugin added support for virtual presence sensors so I can cut out a few devices and automations on the SmartThings side.

**Comment by iklein99** [comment]
My plugin is designed to bring Smartthings devices into Home Kit.  I'm not sure if these virtual presence sensors are in smartthings based on your description, or in home kit.  I don't push anything into smartthings.

**Comment by kendalvandyke** [comment]
I'm suggesting that you expose a SmartThings virtual presence sensor to HomeKit. The virtual presence sensor has an on/off switch; on causes the sensor to report as present and off as not present. I want to use HomeKit automations to turn on or off the virtual sensor when someone with their iPhone arrives or leaves.

**Comment by iklein99** [comment]
Ok.  I'll take a look at it.  I'll need you to test it out for me.

**Comment by firstspencer** [comment]
Hey guys. I’m at a trade show so I’m out of pocket until Thursday, but I see that there was a plugin update and I applied it and my contacts are still not showing. I’ll troubleshoot later this week and catch up on the thread, and keep copying me, but I just wanted to say thanks to Klein for this outstanding effort. No other plugin is doing this since Samsung changed their platform. I did change one of the contacts to be a switch and then it came over into HomeKit so I know that I have everything generally setup correctly. Catch you guys in a few days. Darrell SpencerSent from my iPhoneOn Oct 3, 2022, at 2:40 PM, iklein99 ***@***.***> wrote:﻿
Ok.  I'll take a look at it.  I'll need you to test it out for me.

**Comment by firstspencer** [comment]
I use a plugin called “Dummy” to create dummy switches to do the automation you’re talking about. Darrell SpencerSent from my iPhoneOn Oct 3, 2022, at 1:59 PM, Kendal Van Dyke ***@***.***> wrote:﻿
I'm suggesting that you expose a SmartThings virtual presence sensor to HomeKit. The virtual presence sensor has an on/off switch; on causes the sensor to report as present and off as not present. I want to use HomeKit automations to turn on or off the virtual sensor when someone with their iPhone arrives or leaves.

**Comment by iklein99** [comment]
Added support in 1.4.0.  Let me know how it works.  I will leave this open for a couple of days.  If I don't hear anything, I'll be closing it.

**Comment by kendalvandyke** [comment]
Thanks for doing this! I see all SmartThings presence sensors in HomeBridge, but nothing shows up in HomeKit. Guessing that HomeKit doesn't understand presence sensors? The Virtual Presence sensor in SmartThings acts as both a presence sensor and a switch, so what I'd expect is that it at least shows up as a switch in HomeKit, e.g. using HomeKit to toggle the switch on would reflect as on/present in SmartThings.

**Comment by iklein99** [comment]
It looks like an Occupancy Sensor in Home Kit.  You can use it to set up automations.

**Comment by kendalvandyke** [comment]
I'm not seeing any of the SmartThings presence sensors show up as Occupancy sensors in HomeKit. I DO see them in my HomeBridge accessories list, though. Am I missing something?

**Comment by iklein99** [comment]
If you go to add an automation in the Home app on your phone, and look at the sensors, you will see them.  You don't see them as devices in the app that you can control.  But you can select them when creating an animation.

**Comment by iklein99** [comment]
Try looking at IFTTT.  What you want me to do is fairly custom.  What I implemented was to allow a presence sensor to act as an occupancy sensor in Home Kit.  This will allow you to automate something in Home kit.  You probably can get this to work with IFTTT.

**Comment by veonua** [comment]
works for me, thanks 👍
