### ISSUE TITLE
'Saturation' warning

### ISSUE THREAD

**Issue by drpimples** [iklein99/homebridge-smartthings#40]
I've been getting this warning many times over but I'm not sure it affects the functioning of the plugin.  Anything I should adjust in my settings?

[10/7/2022, 10:46:20 PM] [homebridge-smartthings-ik] This plugin generated a warning from the characteristic 'Saturation': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://homebridge.io/w/JtMGR for more info.

**Comment by iklein99** [comment]
What is 'Saturation'?  What kind of accessory?

**Comment by drpimples** [comment]
I copied and pasted the warning exactly.  I assume it means a parameter for a light.  As you can see it doesn’t mention the actual device.  I’ve ignored all the Hue lights I have on SmartThings so all that’s left as far as accessories being controlled on SmartThings are Zwave switches and dimmers, a few Zigbee color bulbs, a Zwave valve, zwave and zigbee motion sensors and leak detectors.

- Chris
Sent with Spark

**Comment by drpimples** [comment]
I copied and pasted the warning exactly.  I assume it means a parameter for a light.  As you can see it doesn’t mention the actual device.  I’ve ignored all the Hue lights I have on SmartThings so all that’s left as far as accessories being controlled on SmartThings are Zwave switches and dimmers, a few Zigbee color bulbs, a Zwave valve, zwave and zigbee motion sensors and leak detectors.

- Chris

**Comment by iklein99** [comment]
Ok.  I’ll take a lookSent from my iPhoneOn Oct 8, 2022, at 9:29 AM, drpimples ***@***.***> wrote:﻿
I copied and pasted the warning exactly.  I assume it means a parameter for a light.  As you can see it doesn’t mention the actual device.  I’ve ignored all the Hue lights I have on SmartThings so all that’s left as far as accessories being controlled on SmartThings are Zwave switches and dimmers, a few Zigbee color bulbs, a Zwave valve, zwave and zigbee motion sensors and leak detectors.

- Chris

**Comment by iklein99** [comment]
I haven't been able to reproduce this.  I'm closing.
