### ISSUE TITLE
Door lock shows stuck in "unlocking" state even after auto-lock has happened

### ISSUE THREAD

**Issue by mfw2010** [iklein99/homebridge-smartthings#42]
I have a Yale Smart Lock with Z-wave module and it all works really well. The only issue now is that the lock state is stuck on "unlocking" even after the auto-lock has taken place. It seems like the event from smartthings does not then update the lock status.

**Comment by mfw2010** [comment]
homebridge-smartthings-ik v1.4.4 - assume that's the latest which also has the fix?

**Comment by mfw2010** [comment]
I think one of the events has an issue. When I unlock from the SmartThings app, HomeKit received a target state of “locking” and is stuck in that state. Eventually when I then lock via the SmartThings app, HomeKit successfully updates the status to locked

**Comment by iklein99** [comment]
Ok.  I’ll look into it.

**Comment by iklein99** [comment]
I reproduced the issue.  I never use Smartthings app to control my devices, so I never saw this.  I'll have a fix soon.

**Comment by mfw2010** [comment]
That’s great thank you. I never use SmartThings app to control devices either. This was behaving the same way even in case of auto locking, glad you can reproduce it.

**Comment by iklein99** [comment]
Should be fixed in 1.4.5.  Give it a shot.

**Comment by mfw2010** [comment]
That seems to have now been fixed, thank you that was quick!
