### ISSUE TITLE
Support for Smart Wall Oven Model NV51K6650SG

### ISSUE THREAD

**Issue by soxrok2212** [iklein99/homebridge-smartthings#43]
Hi there! I'm looking to see if it'd be possible to add support for my smart oven model NV51K6650SG. I have it working with the SmartThings app, but looking to integrate it into Homebridge/Homekit where everything else resides.

Any chance you'd be interested in taking this on? I can provide you with whatever it is you need.

**Comment by soxrok2212** [comment]
Here's the model page: https://www.samsung.com/us/home-appliances/wall-ovens/single/nv51k6650sg-aa-nv51k6650sg-aa/

**Comment by iklein99** [comment]
I’d need to see what the oven looks like in Smartthings.

If you do this in Homebridge:

1. Delete the logs
2. Put Homebridge into Debug mode
3. Restart Homebridge
4. After about 30 seconds, or so, turn debug mode off and restart homebridge
5. Send me the logs.  You can email them direct to me at ***@***.*** ***@***.***>

**Comment by soxrok2212** [comment]
Sent you an e-mail with hopefully everything you need!

**Comment by iklein99** [comment]
At this time, Apple Home Kit does not support an oven.  I haven't done anything with custom devices and don't know how home kit would support a custom services.  As such, I'm going to close this issue.
