### ISSUE TITLE
please add support for power/energy metter

### ISSUE THREAD

**Issue by vinhthaipham** [iklein99/homebridge-smartthings#44]
specifically Aeotec - Z-Wave Clamp Power Meter

**Comment by iklein99** [comment]
At this time, Apple Home Kit doesn't support this type of device.  I haven't done anything with custom devices yet and don't know what Home kit would do with them.  As such, I'm closing this for now.

**Comment by philmehew** [comment]
Not sure if is useful information, but I use a virtual lock on SmartThings and using your HomeBridge integration allows me to see it in HomeKitOn 16 Oct 2022, at 12:22, iklein99 ***@***.***> wrote:﻿
At this time, Apple Home Kit doesn't support this type of device.  I haven't done anything with custom devices yet and don't know what Home kit would do with them.  As such, I'm closing this for now.
