### ISSUE TITLE
Momentary Switches

### ISSUE THREAD

**Issue by sebastiangoldstein** [iklein99/homebridge-smartthings#45]
**Is your feature request related to a problem? Please describe:**
Please add support for SmartThings Momentary Switches  

**Describe the solution you'd like:**
Add to new release

**Describe alternatives you've considered:**

**Additional context:**

**Comment by veonua** [comment]
As far as know there is no such kind of devices as momentary switch in HomeKit 

https://developer.apple.com/documentation/homekit/hmaccessorycategory/accessory_category_types

also momentary is deprecated in the ST .

**Comment by iklein99** [comment]
At this time, I haven't done anything with custom services in home kit.  I don't know how they behave, and as @veonua says, there is no support for that type of device.
