### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'hue')

### ISSUE THREAD

**Issue by veonua** [iklein99/homebridge-smartthings#47]
**Describe The Bug:**
**To Reproduce:**

I've added several IKEA lamps with color temperature only 

**Expected behavior:**
ignore hue for color temp lights

**Logs:**

> [17/10/2022, 12:34:28] TypeError: Cannot read properties of undefined (reading 'hue')
>     at /var/lib/homebridge/node_modules/homebridge-smartthings-ik/src/lightBulbAccessory.ts:270:51
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> [17/10/2022, 12:34:29] TypeError: Cannot read properties of undefined (reading 'hue')
>     at /var/lib/homebridge/node_modules/homebridge-smartthings-ik/src/lightBulbAccessory.ts:270:51
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> [17/10/2022, 12:34:29] TypeError: Cannot read properties of undefined (reading 'hue')
>     at /var/lib/homebridge/node_modules/homebridge-smartthings-ik/src/lightBulbAccessory.ts:270:51
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> [17/10/2022, 12:34:29] [Smartthings(new)] getSaturation() FAILED for lampC. Comm error.
> [17/10/2022, 12:34:29] [Smartthings(new)] getSaturation() FAILED for lampR. Comm error.
> [17/10/2022, 12:34:29] [Smartthings(new)] getSaturation() FAILED for lampL. Comm error.

**Environment:**

* **Plugin Version**: 1.4.5
* **Operating System**: Raspbian

**Comment by iklein99** [comment]
I'll look onto this.  The device reports that it supports the colorControl capability, but it isn't supporting the required parameters of saturation and hue.  I'll see what I can do.  May be a little while.

**Comment by veonua** [comment]
it's cold warm light . it doesn't have hue . only color temperature

**Comment by iklein99** [comment]
Do me a favor.  Clear your logs, put Homebridge into debug mode, start it up and let it run for about 30 seconds.  Look for the DEVICE DATA: log entry for the device and send that over.  Unless there is a bug here, the device is reporting that is support colorControl which is Hue and Saturation.  If it reports that but doesn’t really support it, that is the problem.  Let me know.

**Comment by iklein99** [comment]
Closing for now.  Reopen if you can send me the log.
