### ISSUE TITLE
Donation Support in HomeBridge UI

### ISSUE THREAD

**Issue by cms365** [iklein99/homebridge-smartthings#53]
The dedication to improving and supporting this plugin is first class. You should add donation capabilities so people can show their appreciation. Even if doing for fun, can’t hurt to allow people to show their appreciation.

**Comment by dmurchie** [comment]
Just installed after watching the project for a few weeks. Pretty slick.

**Comment by iklein99** [comment]
Working on adding this.  Thanks for the advice.

**Comment by iklein99** [comment]
Its there.  Fee free to use!!
