### ISSUE TITLE
Recommended Access Token Settings?

### ISSUE THREAD

**Issue by dmurchie** [iklein99/homebridge-smartthings#54]
Just installed the plugin and I'm excited. Regarding my access token: there are a LOT of checkboxes on Samsung's token creation page. Any recommendations on what to check besides "Devices" (and "Locations" if need as described in README)?

Reason I ask: all of my switches/bulbs were added to HK, but a few SmartThings leak and motion sensors are nowhere to be found. I'm wondering if that's something to do with my token (e.g., Device Profiles).

THANKS for your efforts - and I'm available to test if needed (I have numerous GE/Jasco/HomeSeer switches and a bunch of ST leak and motion sensors).

**Comment by dmurchie** [comment]
1.4.6

**Comment by dmurchie** [comment]
Thanks, and definitely up for testing if you need a volunteer (front-end/light-back-end web developer, which is only to say I can find my way around a little bit).

**Comment by iklein99** [comment]
Motion detectors should work with 1.4.7.  Keep in mind that sensors don't show up in the Home app as normal devices.  You will see them if you add an automation under the sensors.

I haven't implemented leak detectors yet, but I'll have a look.

**Comment by dmurchie** [comment]
Aha, i know nothing! The motion sensors are all there!

I've never had a HK sensor so I wasn't looking in the "right place." Oops...

Thanks so much for the tip.
