### ISSUE TITLE
add IgnoreDevices

### ISSUE THREAD

**Issue by veonua** [iklein99/homebridge-smartthings#6]
**Is your feature request related to a problem? Please describe:**

My Nanoleaf light panels are already in the HomeKit (via direct integration)
Connecting ST creates a device's twin

**Describe the solution you'd like:**

please add ignore devices section for virtual devices and devices already integrated

"platform": "HomeBridgeSmartThings",
"IgnoreDevices": [ "Light Panels" ]

**Comment by iklein99** [comment]
I'll look into that.

**Comment by iklein99** [comment]
This has been completed in version 1.1.12.
