### ISSUE TITLE
Temperature in Celsius

### ISSUE THREAD

**Issue by veonua** [iklein99/homebridge-smartthings#62]
>>      return (status.temperatureMeasurement.temperature.value as number -  32) * (5/9) ; // Convert to Celcius

For some reason, the service assumes that Smartthings reposts in Fahrenheit. ST response has the unit value. and my value is already in Celcius

**Comment by iklein99** [comment]
Thanks for the catch.  I'll fix shortly.

**Comment by iklein99** [comment]
Ok.  Try 1.4.9

**Comment by veonua** [comment]
great thanks
