### ISSUE TITLE
frequent warning message related to characteristic

### ISSUE THREAD

**Issue by yasuhiroi-novi** [iklein99/homebridge-smartthings#69]
**Describe The Bug:**
When using an ambient light sensor( Aeotec Multisensor 6 in my case), homebridge-smartthings plugin generates warning messages so frequently. 
It occurs mainly in nighttime, since the waring message was complaining that sensor value 0 is exceeding minimum allowed value. 

**To Reproduce:**
1. Connecting Aeotec Multisensor 6 with Smartthings. 
2. Put that sensor in a completely dark environment or just disconnect it from the power source.

**Expected behavior:**
The plugin should accept 0 as normal sensor value. If it is not feasible can me add offset to sensor value to dismiss this warning message? 

**Logs:**

[10/29/2022, 11:02:03 PM] [homebridge-smartthings-ik] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://homebridge.io/w/JtMGR for more info.

**Plugin Config:**
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": 
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 10,
            "PollDoorsSeconds": 10,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "platform": "HomeBridgeSmartThings",
            "_bridge": {
                "username": "XXXX",
                "port": XXX
            }
**Environment:**

* **Plugin Version**: homebridge-smartthings-ik v1.4.9
* **Homebridge Version**: 1.5.1
* **Node.js Version**: v.16.18.0
* **NPM Version**: 8.5.1
* **Operating System**:  Ubuntu Jammy Jellyfish (22.04.1 LTS)

**Comment by iklein99** [comment]
Fixed in 1.4.10
