### ISSUE TITLE
Loading Accessories and Scenes...Forever

### ISSUE THREAD

**Issue by jplwoodward** [iklein99/homebridge-smartthings#72]
**Describe The Bug:**
When the Home app launches it is stuck forever on "Loading Accessories and Scenes"

**To Reproduce:**
I added a Minoston "Outdoor Plug Energy Monitor" to Smatthings.  It worked fine with Smartthings.  I then restarted Homebridge when running your 1.4.10.  The outlet showed up i the Home app.  I edited to remove it from Favorites and Status.  After doing so the Home app showed "Loading Accessories and Scenes"...forever.

**Expected behavior:**
Home should continue operating.  Quitting Home and restarting did not fix it.  I edited your Config to ignore it, and upgraded to 1.4.11 and restarted Homebridge.  This did not fox the problem

**Logs:**
[10/31/2022, 2:43:24 PM] [Smartthings New] Registering new accessory: Front Door Spotlight
after update:
[10/31/2022, 2:48:37 PM] [Smartthings New] Will unregister Front Door Spotlight

**Plugin Config:**

"name": "Smartthings New",
            "BaseURL": "https://api.smartthings.com/v1/",
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 0,
            "PollDoorsSeconds": 0,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "IgnoreDevices": [
                "MAIN Virtual Devices",
                "FR Pendant",
                "FR Outer",
                "FR Inner",
                "Wyze Plug",
                "FR Sconces ON random",
                "FR Sconces OFF random",
                "Bedroom ON random",
                "Bedroom OFF random",
                "Basement Thermostat",
                "Laundry Leak",
                "Boiler Leak",
                "Water Heater Leak",
                "Front Door Spotlight"
            ],
            "_bridge": {
                "username": "0E:10:B6:52:36:06",
                "port": 41029
            },
            "platform": "HomeBridgeSmartThings"
        },

**Comment by jplwoodward** [comment]
After restarting my phone and launching the home app over and over...the hang eventually went away.  I un-ignored the outlet in you config then restarted Homebridge.  Now all is fine.  Go figure!

**Comment by iklein99** [comment]
Sounds like a home app issue.  Closing.
