### ISSUE TITLE
Changing colour on a lightbulb doesn't work

### ISSUE THREAD

**Issue by obrassard** [iklein99/homebridge-smartthings#96]
**Describe The Bug:**

When trying to change the colour of a RGB lightbulb the Home app, an error is thrown by the plugin.
It seem that there is an issue with the API call that is made to Smart Things API when trying to set a new hue or saturation.

**To Reproduce:**

1. Pair a RGB Light Bulb with Samsung SmartThings app
   * in my case it is a Teckin LightBulb paired with SmartLife (Tuya) and connected to SmartThings
2. When the device appear in the Home app, click on the RGB light and try changing the colour
3. The colour of the light bulb does not change an error is printed in the Homebridge Console

Note : Changing the colour in the SmartThings app works properly.

**Expected behavior:**

The colour of the lightbulb should be updated properly like it is when changing the colour directly in SmartThings

**Logs:**

<img width="1306" alt="Capture d’écran, le 2022-11-28 à 23 42 25" src="https://user-images.githubusercontent.com/17227551/204440897-abb5d80f-32fc-4d4e-8d0c-ff94b10c2bc0.png">

**Plugin Config:**

```json
{
    "bridge": { ...
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "...",
            "GarageDoorMaxPoll": 0,
            "PollLocksSeconds": 0,
            "PollDoorsSeconds": 0,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 1,
            "IgnoreDevices": [
                "Piscine"
            ],
            "platform": "HomeBridgeSmartThings"
        }
    ]
}
```

**Environment:**

* **Plugin Version**: v1.4.15
* **Homebridge Version**: 1.6.0
* **Node.js Version**: v18.12.1
* **NPM Version**: 8.19.2
* **Operating System**: Docker on RaspberryPI OS

**Comment by obrassard** [comment]
Now worry, I started a thread on SmartThings Developers Community to see if they can do something on their side 

https://community.smartthings.com/t/smartthings-edge-developer-beta-known-issues-and-bug-tracking/230389

**Comment by iklein99** [comment]
I'm going to fix this by using the setColor command if I detect an error sending individual hue and saturation.  Will need you to test for me.

**Comment by obrassard** [comment]
@iklein99 Perfect, I think that's the best solution considering the information we have. I'm curious to see your PR, as I had tried to do this fix the other day, but wasn't sure how to proceed!

**Comment by iklein99** [comment]
Fixed in 1.4.17.  Try it out and let me know.

**Comment by obrassard** [comment]
@iklein99 Unfortunately it does not work
<img width="1119" alt="Capture d’écran, le 2022-12-11 à 11 32 03" src="https://user-images.githubusercontent.com/17227551/206916226-0922e883-487a-47b8-a2ef-ed709da3cd87.png">

**Comment by iklein99** [comment]
Ok.  Think I found the issue.  Try 1.4.18.

**Comment by obrassard** [comment]
@iklein99 It works ! Although, it seems that some colors are weird (between what I choose in the Home app, and the color that is really on the bulb), but it is probably not related to your fix

<img width="1220" alt="Capture d’écran, le 2022-12-11 à 19 10 29" src="https://user-images.githubusercontent.com/17227551/206937484-571dad89-6c8b-4e06-9c52-046ddefc8c95.png">

**Comment by obrassard** [comment]
> it seems that some colors are weird 

Especially when switching quickly between colours
