### ISSUE TITLE
Samsung Zigbee Buttons

### ISSUE THREAD

**Issue by virtualjad** [iklein99/homebridge-smartthings#97]
First of all, thanks for all the effort going into this plugin!

I can't get any of my smartthings buttons to show up in Home. I do see the associated temp gauges for each button, but not the button device itself. Is this a known limitation? If not currently supported, any plans to add?

Thanks!
Jad

**Comment by iklein99** [comment]
Currently not supported.  Buttons require the use of a webhook smart app in order to get button press updates sent from Smartthings.  I'm working on this now, but, it will not be a free, since I need to run an app in the cloud to receive the events from Smartthings.
